### ISSUE TITLE
voPersonApplicationUID, more elaborate referencing needed?

### ISSUE THREAD

**Issue by surfnet-niels** [voperson/voperson#10]
the app-* is a very short and simplified reference to an application. I could image a multi tenant system one might want a more elaborate way to reference the target application, e.g. with a urn of entityid. I do not see however how that could be done in a easy way?

**Comment by boshrin** [comment]
After some discussion, we've decided to defer to avoid making the pilot phase to complex. That said, we did float some ideas for later. The best option at the moment would be to base64 encode a DN or entity ID or whatever and then use that as the application label. You could even do this now within a deployment since `applicationLabel` is opaque.

`voPersonApplicationUID;app-Y249bXlhcHBpbmZvLCBkYz1kb21haW4sIGRjPWVkdQ==: jsmith`

RFC 4512 says these should be "short", but doesn't seem to specify a maximum length.

**Comment by surfnet-niels** [comment]
Ok WFM
